services:
  server:
    build:
      context: ./server/
    command: npm start
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client/
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"